version: '3'

services:
  #Database
  db:
    image: mysql:5.7
    volumes:
      - db_data: /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  #phpadmin
  phpadmin:
    depends_on:
      - db
    image: phpadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - wpsite
  #Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes: 
      - db_data: /var/www/html
      - ./src: /var/www/html
    ports:
      - '8008:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
